### PR TITLE
Native phone login

### LINKED ISSUE #165: Login with phone number
1. **What happens**: 
    - Only FB is allowed atm
    
2. **What was expected**:
    - FB used as backup, phone number as main login method

3. **How to reproduce**: 
    1. Launch

4. **Environment**: 
    - Sailfish OS version: 2.1.4
    - Sailfish OS hardware: Xperia X

### PR DESCRIPTION
**Pull request by daneos**
1. **Explanation**: 
    This PR adds a welcome page, that lets you choose between using Facebook login and phone number, and everything that's needed to successfully log in by phone. There are also some minor improvements for the Facebook login page.

2. **Fixed issues**: 
    - Fixed #165 

3. **Testing environment**: 
    - Sailfish OS version: 3.0.1.14
    - Sailfish OS hardware: Xperia XA2 Plus

Just as a note, this is my first ever piece of code written for Sailfish, so I probably done some terrible things in here :)

### CODE REVIEW

**Comment by DylanVanAssche** [comment]
Thanks for your PR! I will review it ASAP :)
This is a feature I always wanted to implement but never could :)

**Comment by daneos** [comment]
> Facebook login is broken: `api.login` call seems to be wrong?

I might have broken something with default argument values, never used this feature in C++ before. I also didn't test the Facebook login, as my account is not linked with Facebook. I just realized, though, I can create another account that will allow Facebook login :)

> The welcome page is still in the PageStack. When you swipe through the different views   (recommendations, matches and profile), you can swipe back to the welcome page. If I'm not wrong, the welcome page, should be remove from the PageStack when the login is successfull.

I actually ran into this problem today. I think there may be more bugs related to Sailfish specific features, as I never used it before.

> Phone login works nice :) However, I would change the `locale=sv_SE` to `locale=en_GB` to receive SMS token in English.

I just used the URLs I got by wiresharking the original client :) I assumed AccountKit uses my account's locale without close examination of the URL. I think the best approach would be to use locale currently set on the device.

I will probably have some time next week, so I'll try to fix these issues. Thanks for the review!

**Comment by DylanVanAssche** [comment]
> > Facebook login is broken: `api.login` call seems to be wrong?
> 
> I might have broken something with default argument values, never used this feature in C++ before. I also didn't test the Facebook login, as my account is not linked with Facebook. I just realized, though, I can create another account that will allow Facebook login :)
> 
> > The welcome page is still in the PageStack. When you swipe through the different views   (recommendations, matches and profile), you can swipe back to the welcome page. If I'm not wrong, the welcome page, should be remove from the PageStack when the login is successfull.
> 
> I actually ran into this problem today. I think there may be more bugs related to Sailfish specific features, as I never used it before.
> 
> > Phone login works nice :) However, I would change the `locale=sv_SE` to `locale=en_GB` to receive SMS token in English.
> 
> I just used the URLs I got by wiresharking the original client :) I assumed AccountKit uses my account's locale without close examination of the URL. I think the best approach would be to use locale currently set on the device.
> 
> I will probably have some time next week, so I'll try to fix these issues. Thanks for the review!

Yeah sure :+1:  I'm happy to help you if you're stuck with something :tada:

**Comment by daneos** [comment]
I think all problems are now fixed.
Facebook login works, it seems the default arguments don't really work (or at least I can't use them :) )
The page stack is cleared when authenticated.
Locale for the SMS message is now taken from system locale.

I also changed the name of Facebook login page to be more descriptive and changed the page displayed after logout to welcome page.

**Comment by DylanVanAssche** [comment]
Great! Works fine! Thank you! Merging in `development`!

**Pull request merged**
